services:
  - type: web
    name: ai-resume-analyzer
    env: python
    plan: free
    buildCommand: |
      pip install -r App/requirements.txt
      python -m spacy download en_core_web_sm
      python -m nltk.downloader stopwords

    startCommand: |
      python -m uvicorn App.api:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        value: cv
      - key: MYSQL_PORT
        value: 3306
